name: Test

on: [push]

jobs:
  test:
    # где заускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v4
      # настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      # запускаем тесты
      - run: ./gradlew clean test